@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Interface ReadOnlyContactList <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface ReadOnlyCommandHistory <<Interface>>
Class Model
Class ContactList
Class ReadOnlyContactList
Class UserPrefs
Class CommandHistory
Class ProfilePictureSyncModel
Class ModelManager
Class ReadOnlyUserPrefs

Class "{abstract}\nHandle" as Handle
Class UniquePersonList
Class Person
Class Name
Class Phone
Class Remark
Class ProfilePicture
Class Facebook
Class Instagram
Class Telegram
Class TikTok
Class Twitter
Class Dates
Class Date
Class Tag
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Model .d.> ReadOnlyContactList
Model .d.> ReadOnlyUserPrefs
Model .d.> ReadOnlyCommandHistory
ReadOnlyContactList -[hidden]r> ReadOnlyUserPrefs
ReadOnlyUserPrefs -[hidden]r> ReadOnlyCommandHistory

ContactList .u.|> ReadOnlyContactList
UserPrefs .u.|> ReadOnlyUserPrefs
CommandHistory .u.|> ReadOnlyCommandHistory

ModelManager -u-> "1" ContactList
ModelManager -u-> "1" UserPrefs
ModelManager -u-> "1" CommandHistory
ModelManager -u-> "1" ProfilePictureSyncModel

ModelManager ...u|> Model
ModelManager -->"~*filtered" Person

ContactList *---> "1" UniquePersonList
UniquePersonList -r> "~*all" Person
UniquePersonList -[hidden]-> ContactList

Person *----> "0..1" Facebook
Person *----> "0..1" Instagram
Person *----> "0..1" Telegram
Person *----> "0..1" TikTok
Person *----> "0..1" Twitter
Facebook -d-|> Handle
Instagram -d-|> Handle
Telegram -d-|> Handle
TikTok -d-|> Handle
Twitter -d-|> Handle

Person *---> "0..1" Remark
Person *---> "0..1" ProfilePicture
Person *--> "0..*" Tag

Person *--> "1" Name
Person *--> "1" Phone
Person *-r-> "1" Dates
ProfilePictureSyncModel -[hidden]d> Date
Dates *-u-> "0..*" Date

@enduml
