@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

Interface Storage <<Interface>>
Class StorageManager

package "ContactList Storage" #F4F6F6{
Interface ContactListStorage <<Interface>>
Class JsonContactListStorage
Class JsonSerializableContactList
Class JsonAdaptedPerson
Class JsonAdaptedTag
Class JsonAdaptedDate
}

package "CommandHistory Storage" #F4F6F6{
Interface CommandHistoryStorage <<Interface>>
Class JsonCommandHistoryStorage
Class JsonSerializableCommandHistory
}

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

package "ProfilePicture Storage" #F4F6F6{
Interface ProfilePictureStorage <<Interface>>
Class ProfilePictureStorageManager
}
}


Class HiddenOutside #FFFFFF
HiddenOutside .right.> Storage
StorageManager ..|> Storage
StorageManager .[hidden]up.> Storage

JsonContactListStorage .up.|> ContactListStorage
JsonContactListStorage .down.> JsonSerializableContactList
JsonSerializableContactList -down-> "*" JsonAdaptedPerson
JsonAdaptedPerson -down-> "*" JsonAdaptedTag
JsonAdaptedPerson -down-> "*" JsonAdaptedDate

JsonUserPrefsStorage .up.|> UserPrefsStorage

JsonCommandHistoryStorage .up.|> CommandHistoryStorage
JsonCommandHistoryStorage .down.> JsonSerializableCommandHistory

ProfilePictureStorageManager .up.|> ProfilePictureStorage

StorageManager ---> "1" UserPrefsStorage
StorageManager ---> "1" ContactListStorage
StorageManager ---> "1" CommandHistoryStorage
StorageManager ---> "1" ProfilePictureStorage

Storage ----|> UserPrefsStorage
Storage ----|> ContactListStorage
Storage ----|> CommandHistoryStorage
Storage ----|> ProfilePictureStorage



@enduml
