@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

Interface Storage <<Interface>>
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Interface AddressBookStorage <<Interface>>
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "CommandHistory Storage" #F4F6F6{
Interface CommandHistoryStorage <<Interface>>
Class JsonCommandHistoryStorage
Class JsonSerializableCommandHistory
}

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}
}


Class HiddenOutside #FFFFFF
HiddenOutside .right.> Storage
StorageManager ..|> Storage
StorageManager .[hidden]up.> Storage

JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage .down.> JsonSerializableAddressBook
JsonSerializableAddressBook -down-> "*" JsonAdaptedPerson
JsonAdaptedPerson -down-> "*" JsonAdaptedTag

JsonUserPrefsStorage .up.|> UserPrefsStorage

JsonCommandHistoryStorage .up.|> CommandHistoryStorage
JsonCommandHistoryStorage .down.> JsonSerializableCommandHistory

StorageManager ---> "1" UserPrefsStorage
StorageManager ---> "1" AddressBookStorage
StorageManager ---> "1" CommandHistoryStorage

Storage ----|> UserPrefsStorage
Storage ----|> AddressBookStorage
Storage ----|> CommandHistoryStorage



@enduml
